# Generated by Django 6.0.5 on 2026-05-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cert_delay',
            field=models.IntegerField(default=120000, help_text='Certificate delay in milliseconds. 120000 = 2 minutes.'),
        ),
    ]
