# Generated by Django 6.0.5 on 2026-05-22 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_program_cert_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='program',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cert_delay', models.IntegerField(default=120000, help_text='Certificate delay in milliseconds. 120000 = 2 minutes.')),
                ('cert_template', models.TextField(blank=True, help_text='Base64 encoded certificate background image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='attendance.department')),
            ],
            options={
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.folder'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
