# Generated by Django 6.0.5 on 2026-05-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_department_remove_attendancerecord_program_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='ic_size',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='folder',
            name='ic_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='folder',
            name='ic_y',
            field=models.FloatField(default=53),
        ),
        migrations.AddField(
            model_name='folder',
            name='name_size',
            field=models.FloatField(default=48),
        ),
        migrations.AddField(
            model_name='folder',
            name='name_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='folder',
            name='name_y',
            field=models.FloatField(default=45),
        ),
        migrations.AddField(
            model_name='folder',
            name='show_ic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
