# Generated by Django 6.0.5 on 2026-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_folder_font_family_folder_ic_size_folder_ic_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='event_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='organizer',
            field=models.CharField(default='Perbadanan Labuan', max_length=255),
        ),
    ]
