# Generated by Django 6.0.5 on 2026-05-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_folder_event_date_folder_event_name_folder_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='cert_delay',
            field=models.IntegerField(default=0, help_text='Delay in milliseconds'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='cert_delay',
            field=models.IntegerField(default=0, help_text='Certificate delay in milliseconds. 0 = no delay.'),
        ),
    ]
