# Generated by Django 6.0.5 on 2026-06-03 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancerecord_cert_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='clean_ic_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
