# Generated by Django 6.0.6 on 2026-06-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_abuserequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.department'),
        ),
    ]
